# run: conda env create --file environment.yml
# to update run: conda env update --file environment.yml

name: Transformer
channels:
  - pytorch
  - defaults
dependencies:
  - python>=3.8
  - pytorch>2.0.0
  - torchvision
  - cudatoolkit>=10.2
  - numpy>=1.20.3
  - matplotlib>=3.3.4
  - pandas>=1.2.4
  - scikit-learn>=1.0.2
  - pip>=21.0.1
  - pip:
    - wandb
    - tqdm
    - simple_parsing
    - torch-summary
